# Generated by Django 2.0.3 on 2020-03-28 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('Aid', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('Aname', models.CharField(max_length=255, verbose_name='管理员账号')),
                ('Apassword', models.CharField(max_length=255, verbose_name='管理员密码')),
            ],
            options={
                'db_table': 'AdminUser',
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('Fid', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='id')),
            ],
            options={
                'db_table': 'Collection',
            },
        ),
        migrations.CreateModel(
            name='JobRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('JobPublisher', models.IntegerField(verbose_name='发布人')),
                ('JobApply', models.IntegerField(verbose_name='接单人')),
            ],
            options={
                'db_table': 'JobRelation',
            },
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('Jid', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('Jobname', models.CharField(max_length=255, verbose_name='岗位')),
                ('Jobloc', models.CharField(max_length=255, verbose_name='详细工作地址')),
                ('JobSalary', models.CharField(max_length=255, verbose_name='薪资')),
                ('JobContact', models.CharField(max_length=255, verbose_name='联系人')),
                ('Jobphonenumber', models.CharField(max_length=255, verbose_name='联系人电话')),
                ('JobHired', models.CharField(default='0', max_length=255, verbose_name='订单是否有效')),
                ('JobDeatails', models.TextField(max_length=500, verbose_name='工作内容')),
                ('Jobtime', models.DateTimeField(auto_now=True, max_length=255, verbose_name='发布时间')),
                ('Province_and_city', models.CharField(max_length=255, null=True, verbose_name='省市区')),
            ],
            options={
                'db_table': 'Jobs',
            },
        ),
        migrations.CreateModel(
            name='PartTimeUser',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('Pid', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('PUsername', models.CharField(max_length=255, verbose_name='用户名称')),
                ('PPassword', models.CharField(max_length=255, verbose_name='用户密码')),
                ('PSex', models.CharField(max_length=255, verbose_name='用户性别')),
                ('PPhoneNumber', models.CharField(max_length=255, verbose_name='手机号码')),
                ('PIDCard', models.CharField(max_length=255, verbose_name='身份证号')),
                ('PLocation', models.CharField(max_length=255, verbose_name='住址')),
            ],
            options={
                'db_table': 'PartTimeUser',
            },
        ),
        migrations.AddField(
            model_name='jobs',
            name='Puser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parttime.PartTimeUser'),
        ),
        migrations.AddField(
            model_name='collection',
            name='FJobFav',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parttime.PartTimeUser'),
        ),
        migrations.AddField(
            model_name='collection',
            name='Jid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parttime.Jobs'),
        ),
    ]
